/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAlert: typeof import('element-ui/lib/alert')['default']
    ElAvatar: typeof import('element-ui/lib/avatar')['default']
    ElBacktop: typeof import('element-ui/lib/backtop')['default']
    ElBadge: typeof import('element-ui/lib/badge')['default']
    ElButton: typeof import('element-ui/lib/button')['default']
    ElCalendar: typeof import('element-ui/lib/calendar')['default']
    ElCard: typeof import('element-ui/lib/card')['default']
    ElCheckbox: typeof import('element-ui/lib/checkbox')['default']
    ElCollapse: typeof import('element-ui/lib/collapse')['default']
    ElCollapseItem: typeof import('element-ui/lib/collapse-item')['default']
    ElCollapseTransition: typeof import('element-ui/lib/transitions/collapse-transition')['default']
    ElColorPicker: typeof import('element-ui/lib/color-picker')['default']
    ElDropdown: typeof import('element-ui/lib/dropdown')['default']
    ElDropdownItem: typeof import('element-ui/lib/dropdown-item')['default']
    ElDropdownMenu: typeof import('element-ui/lib/dropdown-menu')['default']
    ElForm: typeof import('element-ui/lib/form')['default']
    ElFormItem: typeof import('element-ui/lib/form-item')['default']
    ElIcon: typeof import('element-ui/lib/icon')['default']
    ElImage: typeof import('element-ui/lib/image')['default']
    ElInput: typeof import('element-ui/lib/input')['default']
    ElLink: typeof import('element-ui/lib/link')['default']
    ElMenu: typeof import('element-ui/lib/menu')['default']
    ElMenuItem: typeof import('element-ui/lib/menu-item')['default']
    ElRadio: typeof import('element-ui/lib/radio')['default']
    ElRadioGroup: typeof import('element-ui/lib/radio-group')['default']
    ElSlider: typeof import('element-ui/lib/slider')['default']
    ElSubmenu: typeof import('element-ui/lib/submenu')['default']
    ElTag: typeof import('element-ui/lib/tag')['default']
    Lottie: typeof import('./../components/Lottie/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
  }
}
